# Étape 1 : Construire l'application
FROM maven:3.8.5-eclipse-temurin-17 AS build

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Installer Node.js et npm pour ARM
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm@latest && \
    apt-get clean

# Copier les fichiers Maven
COPY pom.xml ./
COPY .mvn/ .mvn
COPY mvnw ./

# Résoudre les dépendances Maven avec cache
RUN ./mvnw dependency:resolve -DskipTests

# Copier les fichiers Angular et Webpack
COPY package.json package-lock.json angular.json tsconfig.json tsconfig.app.json tsconfig.spec.json ./
COPY webpack/ webpack/

# Installer les dépendances npm
RUN npm ci

# Vérifier que Webpack est correctement configuré
RUN ls webpack/ && cat webpack/webpack.custom.js

# Copier le code source de l'application
COPY src ./src

# Compiler et packager l'application
RUN ./mvnw clean package -DskipTests
RUN npm run webapp:build -- --configuration production || (cat /app/angular-errors.log && exit 1)

# Étape 2 : Exécuter l'application
FROM openjdk:17-jdk-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier jar généré depuis l'étape précédente
COPY --from=build /app/target/StarMind.jar ./StarMind.jar

# Définir les variables d'environnement nécessaires
ENV SPRING_PROFILES_ACTIVE=prod
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/starmind
ENV SPRING_DATASOURCE_USERNAME=postgres
ENV SPRING_DATASOURCE_PASSWORD=postgres

# Exposer le port de l'application
EXPOSE 8080

# Commande pour exécuter l'application
CMD ["java", "-jar", "StarMind.jar"]
