package com.nova.star.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GlobalChatAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalChatAllPropertiesEquals(GlobalChat expected, GlobalChat actual) {
        assertGlobalChatAutoGeneratedPropertiesEquals(expected, actual);
        assertGlobalChatAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalChatAllUpdatablePropertiesEquals(GlobalChat expected, GlobalChat actual) {
        assertGlobalChatUpdatableFieldsEquals(expected, actual);
        assertGlobalChatUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalChatAutoGeneratedPropertiesEquals(GlobalChat expected, GlobalChat actual) {
        assertThat(expected)
            .as("Verify GlobalChat auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalChatUpdatableFieldsEquals(GlobalChat expected, GlobalChat actual) {
        assertThat(expected)
            .as("Verify GlobalChat relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalChatUpdatableRelationshipsEquals(GlobalChat expected, GlobalChat actual) {
        // empty method
    }
}
