package com.nova.star.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IdeaChatAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdeaChatAllPropertiesEquals(IdeaChat expected, IdeaChat actual) {
        assertIdeaChatAutoGeneratedPropertiesEquals(expected, actual);
        assertIdeaChatAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdeaChatAllUpdatablePropertiesEquals(IdeaChat expected, IdeaChat actual) {
        assertIdeaChatUpdatableFieldsEquals(expected, actual);
        assertIdeaChatUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdeaChatAutoGeneratedPropertiesEquals(IdeaChat expected, IdeaChat actual) {
        assertThat(expected)
            .as("Verify IdeaChat auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdeaChatUpdatableFieldsEquals(IdeaChat expected, IdeaChat actual) {
        assertThat(expected)
            .as("Verify IdeaChat relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdeaChatUpdatableRelationshipsEquals(IdeaChat expected, IdeaChat actual) {
        // empty method
    }
}
