package com.nova.star.domain;

import static com.nova.star.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class IdeaHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdeaHistoryAllPropertiesEquals(IdeaHistory expected, IdeaHistory actual) {
        assertIdeaHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertIdeaHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdeaHistoryAllUpdatablePropertiesEquals(IdeaHistory expected, IdeaHistory actual) {
        assertIdeaHistoryUpdatableFieldsEquals(expected, actual);
        assertIdeaHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdeaHistoryAutoGeneratedPropertiesEquals(IdeaHistory expected, IdeaHistory actual) {
        assertThat(expected)
            .as("Verify IdeaHistory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdeaHistoryUpdatableFieldsEquals(IdeaHistory expected, IdeaHistory actual) {
        assertThat(expected)
            .as("Verify IdeaHistory relevant properties")
            .satisfies(e -> assertThat(e.getAction()).as("check action").isEqualTo(actual.getAction()))
            .satisfies(e ->
                assertThat(e.getActionDate())
                    .as("check actionDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getActionDate())
            )
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getRewardType()).as("check rewardType").isEqualTo(actual.getRewardType()))
            .satisfies(e -> assertThat(e.getLikes()).as("check likes").isEqualTo(actual.getLikes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdeaHistoryUpdatableRelationshipsEquals(IdeaHistory expected, IdeaHistory actual) {
        assertThat(expected)
            .as("Verify IdeaHistory relationships")
            .satisfies(e -> assertThat(e.getIdea()).as("check idea").isEqualTo(actual.getIdea()));
    }
}
