package com.nova.star.domain;

import static com.nova.star.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class LikeHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeHistoryAllPropertiesEquals(LikeHistory expected, LikeHistory actual) {
        assertLikeHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertLikeHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeHistoryAllUpdatablePropertiesEquals(LikeHistory expected, LikeHistory actual) {
        assertLikeHistoryUpdatableFieldsEquals(expected, actual);
        assertLikeHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeHistoryAutoGeneratedPropertiesEquals(LikeHistory expected, LikeHistory actual) {
        assertThat(expected)
            .as("Verify LikeHistory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeHistoryUpdatableFieldsEquals(LikeHistory expected, LikeHistory actual) {
        assertThat(expected)
            .as("Verify LikeHistory relevant properties")
            .satisfies(e -> assertThat(e.getAction()).as("check action").isEqualTo(actual.getAction()))
            .satisfies(e ->
                assertThat(e.getActionDate())
                    .as("check actionDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getActionDate())
            )
            .satisfies(e -> assertThat(e.getOldLikes()).as("check oldLikes").isEqualTo(actual.getOldLikes()))
            .satisfies(e -> assertThat(e.getNewLikes()).as("check newLikes").isEqualTo(actual.getNewLikes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeHistoryUpdatableRelationshipsEquals(LikeHistory expected, LikeHistory actual) {
        assertThat(expected)
            .as("Verify LikeHistory relationships")
            .satisfies(e -> assertThat(e.getIdea()).as("check idea").isEqualTo(actual.getIdea()));
    }
}
