package com.nova.star.domain;

import static com.nova.star.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ProspectBoardAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectBoardAllPropertiesEquals(ProspectBoard expected, ProspectBoard actual) {
        assertProspectBoardAutoGeneratedPropertiesEquals(expected, actual);
        assertProspectBoardAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectBoardAllUpdatablePropertiesEquals(ProspectBoard expected, ProspectBoard actual) {
        assertProspectBoardUpdatableFieldsEquals(expected, actual);
        assertProspectBoardUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectBoardAutoGeneratedPropertiesEquals(ProspectBoard expected, ProspectBoard actual) {
        assertThat(expected)
            .as("Verify ProspectBoard auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectBoardUpdatableFieldsEquals(ProspectBoard expected, ProspectBoard actual) {
        assertThat(expected)
            .as("Verify ProspectBoard relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e ->
                assertThat(e.getCreatedDate())
                    .as("check createdDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedDate())
            )
            .satisfies(e ->
                assertThat(e.getModifiedDate())
                    .as("check modifiedDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getModifiedDate())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectBoardUpdatableRelationshipsEquals(ProspectBoard expected, ProspectBoard actual) {
        // empty method
    }
}
