package com.nova.star.domain;

import static com.nova.star.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ProspectEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectEntryAllPropertiesEquals(ProspectEntry expected, ProspectEntry actual) {
        assertProspectEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertProspectEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectEntryAllUpdatablePropertiesEquals(ProspectEntry expected, ProspectEntry actual) {
        assertProspectEntryUpdatableFieldsEquals(expected, actual);
        assertProspectEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectEntryAutoGeneratedPropertiesEquals(ProspectEntry expected, ProspectEntry actual) {
        assertThat(expected)
            .as("Verify ProspectEntry auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectEntryUpdatableFieldsEquals(ProspectEntry expected, ProspectEntry actual) {
        assertThat(expected)
            .as("Verify ProspectEntry relevant properties")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e ->
                assertThat(e.getCreatedDate())
                    .as("check createdDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedDate())
            )
            .satisfies(e ->
                assertThat(e.getModifiedDate())
                    .as("check modifiedDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getModifiedDate())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProspectEntryUpdatableRelationshipsEquals(ProspectEntry expected, ProspectEntry actual) {
        assertThat(expected)
            .as("Verify ProspectEntry relationships")
            .satisfies(e -> assertThat(e.getProspectBoard()).as("check prospectBoard").isEqualTo(actual.getProspectBoard()));
    }
}
