package com.nova.star.domain;

import static com.nova.star.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class VoteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteAllPropertiesEquals(Vote expected, Vote actual) {
        assertVoteAutoGeneratedPropertiesEquals(expected, actual);
        assertVoteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteAllUpdatablePropertiesEquals(Vote expected, Vote actual) {
        assertVoteUpdatableFieldsEquals(expected, actual);
        assertVoteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteAutoGeneratedPropertiesEquals(Vote expected, Vote actual) {
        assertThat(expected)
            .as("Verify Vote auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteUpdatableFieldsEquals(Vote expected, Vote actual) {
        assertThat(expected)
            .as("Verify Vote relevant properties")
            .satisfies(e -> assertThat(e.getVoteOption()).as("check voteOption").isEqualTo(actual.getVoteOption()))
            .satisfies(e -> assertThat(e.getComment()).as("check comment").isEqualTo(actual.getComment()))
            .satisfies(e ->
                assertThat(e.getCreatedDate())
                    .as("check createdDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedDate())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteUpdatableRelationshipsEquals(Vote expected, Vote actual) {
        assertThat(expected)
            .as("Verify Vote relationships")
            .satisfies(e -> assertThat(e.getIdea()).as("check idea").isEqualTo(actual.getIdea()));
    }
}
